export const chatPhrases = [
  "Hello, how are you?",
  "Good morning!",
  "Good night!",
  "Thank you!",
  "You're welcome.",
  "How can I help you?",
  "What's up?",
  "Take care!",
  "See you soon.",
  "I'm here if you need anything.",
  "Let's meet up later.",
  "Can you send me that file?",
  "I'll get back to you on that.",
  "No worries!",
  "Sounds good to me.",
  "Have a great day!",
  "Let me know if you need help.",
  "I appreciate it.",
  "Happy to help!",
  "What's the plan for today?",
  "Good afternoon!",
  "How was your weekend?",
  "Did you get my message?",
  "Looking forward to it!",
  "Please keep me posted.",
  "I'm running late.",
  "Can we reschedule?",
  "Great job!",
  "I'm excited about this.",
  "That makes sense.",
  "Please let me know your thoughts.",
  "I'll handle it.",
  "Could you clarify that?",
  "Sorry for the inconvenience.",
  "Thank you for your patience.",
  "I'm on it!",
  "I'll take care of it.",
  "Let's catch up soon.",
  "How does that sound?",
  "I'm not sure, let me check.",
  "Do you have a minute?",
  "I'll send you the details.",
  "Just a quick reminder.",
  "I’ll be there shortly.",
  "Let’s get started!",
  "What time works best for you?",
  "I'm looking into it.",
  "I’ll keep you updated.",
  "That’s a great idea!",
  "Thanks for letting me know.",
  "I'm really sorry about that.",
  "Please feel free to reach out.",
  "I'll double-check and confirm.",
  "Let's do it!",
  "Do you need any help?",
  "That works for me.",
  "Keep up the good work!",
  "I’ll let you know ASAP.",
  "Can you confirm the details?",
  "I’m almost done.",
  "Can we discuss this?",
  "Is everything okay?",
  "Let’s take a break.",
  "I'll take a look at it.",
  "I’m looking forward to it.",
  "Is this urgent?",
  "Please give me a moment.",
  "I'll follow up on that.",
  "That was a great suggestion.",
  "I'll be in touch.",
  "Thank you for understanding.",
  "Let's move forward with it.",
  "I'm glad we could talk.",
  "Do you have any questions?",
  "I’ll check on that.",
  "How can I assist you further?",
  "Thank you for your cooperation.",
  "I’ll keep you posted.",
  "Let’s wrap this up.",
  "I'm ready when you are.",
  "Thank you for your feedback.",
  "Can you explain that again?",
  "I'll need more time.",
  "Let's finalize this.",
  "It's been a pleasure working with you.",
  "I'm sorry for the delay.",
  "Let's touch base later.",
  "That’s very kind of you.",
  "Please keep me informed.",
  "I appreciate your quick response.",
  "Let’s set up a meeting.",
  "Thank you for your support.",
  "Let's review the progress.",
  "Do you have any updates?",
  "I hope you're doing well.",
  "Looking forward to your response.",
  "Please send me the information.",
  "I'm on my way.",
  "Please let me know your availability.",
  "I'll make sure it's done.",
  "Let's take it one step at a time.",
]
